# Generated by Django 3.1.1 on 2020-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='main',
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
