# Generated by Django 3.1.1 on 2020-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200913_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='main',
            new_name='main_tag',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
