# Generated by Django 3.1.1 on 2020-09-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200913_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='main_tag',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.hashtag', verbose_name='Раздел'),
        ),
    ]
