# Generated by Django 3.1.1 on 2020-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200914_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='main_tag',
        ),
        migrations.AddField(
            model_name='membership',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
